book/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('home.urls')),
    path('users/', include('users.urls')),
    path('products/', include('products.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('books/', views.BookListView.as_view(), name='book-list'),
    path('books/create/', views.BookCreateView.as_view(), name='create-book'),
    path('books/<int:pk>/', views.BookDetailView.as_view(), name='book-detail'),
    path('books/<int:pk>/update/', views.BookUpdateView.as_view(), name='book-update'),
    path('books/<int:pk>/delete/', views.BookDeleteView.as_view(), name='book-delete'),
    path('books/<int:pk>/review/add/', views.AddReviewView.as_view(), name='add-review'),
    path('reviews/<int:pk>/update/', views.ReviewUpdate.as_view(), name='review-update'),
    path('reviews/<int:pk>/delete/', views.ReviewDelete.as_view(), name='review-delete'),
]

products/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from users.models import CustomUser
# Create your models here.


class CategoryBooks(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        db_table = 'category_books'

    def __str__(self):
        return self.name


class Language(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        db_table = 'language'

    def __str__(self):
        return self.name


class Books(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    price = models.IntegerField()
    category = models.ForeignKey(CategoryBooks, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='books/', blank=True, null=True)
    page = models.IntegerField()
    book_lang = models.ForeignKey(Language, on_delete=models.DO_NOTHING)

    # created_at = models.DateField(auto_now_add=True, null=True)
    # updated_at = models.DateField(auto_now_add=True, null=True)

    class Meta:
        db_table = 'books'

    def __str__(self):
        return self.title


class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)

    class Meta:
        db_table = 'author'

    def __str__(self):
        return f'{self.first_name} {self.last_name}'


class BookAuthor(models.Model):
    book = models.ForeignKey(Books, on_delete=models.CASCADE)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    class Meta:
        db_table = 'book_author'

    def __str__(self):
        return f'{self.book.title} - {self.author.first_name} {self.author.last_name}'


class Review(models.Model):
    comment = models.CharField(max_length=200)
    star_given = models.IntegerField(
        default=0,
        validators=[
            MaxValueValidator(5),
            MinValueValidator(0)
        ]
     )
    book = models.ForeignKey(Books, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

    class Meta:
        db_table ='review'

    def __str__(self):
        return f'{self.star_given} - {self.book.title} - {self.user.username}'

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.


class CustomUser(AbstractUser):
    image = models.ImageField(upload_to='users_images/', blank=True, null=True)

    class Meta:
        db_table = 'customuser'

    def __str__(self):
        return self.username

templates/book/book_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create Book</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }
        form {
            background-color: #fff;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
            width: 400px;
        }
        h1 {
            color: #333;
            text-align: center;
            margin-bottom: 20px;
        }
        input[type="text"], select {
            width: 100%;
            padding: 10px;
            margin-bottom: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            box-sizing: border-box;
        }
        input[type="submit"] {
            background-color: #007bff;
            color: #fff;
            border: none;
            padding: 10px 20px;
            cursor: pointer;
            border-radius: 5px;
            width: 100%;
        }
        input[type="submit"]:hover {
            background-color: #0056b3;
        }
        label {
            display: block;
            margin-bottom: 5px;
            color: #333;
        }
    </style>
</head>
<body>
    <h1>Create Book</h1>
    <form method="post" enctype="multipart/form-data">

        {% csrf_token %}
        <label for="id_title">Title:</label>
        {{ form.title }}
        <label for="id_description">Description:</label>
        {{ form.description }}
        <label for="id_price">Price:</label>
        {{ form.price }}
        <label for="id_category">Category:</label>
        {{ form.category }}
        <label for="id_image">Image:</label>
        {{ form.image }}
        <label for="id_page">Page:</label>
        {{ form.page }}
        <label for="id_book_lang">Language:</label>
        {{ form.book_lang }}
        <input type="submit" value="Save">
    </form>
    <a href="{% url 'products:book-list' %}">Back to Book List</a>
</body>
</html>

templates/book/book_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete Book</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }
        form {
            background-color: #fff;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
            width: 400px;
            text-align: center;
        }
        h1 {
            color: #333;
            text-align: center;
            margin-bottom: 20px;
        }
        p {
            color: #666;
            margin-bottom: 20px;
        }
        input[type="submit"], a {
            background-color: #007bff;
            color: #fff;
            border: none;
            padding: 10px 20px;
            cursor: pointer;
            border-radius: 5px;
            text-decoration: none;
            margin-right: 10px;
        }
        input[type="submit"]:hover, a:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <h1>Delete Book</h1>
    <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm">
        <a href="{% url 'products:book-detail' object.pk  %}">No</a>
    </form>
</body>
</html>

templates/book/book_list.html
{% extends "base.html" %}

{% block title %} Books {% endblock %}

{% block content %}
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
            display: flex;
            flex-direction: column;
            align-items: center;
        }
        h1 {
            color: #333;
            margin-top: 20px;
        }
        p {
            color: #666;
            margin-bottom: 20px;
        }
        a {
            color: #007bff;
            text-decoration: none;
            margin-bottom: 10px;
        }
        a:hover {
            text-decoration: underline;
        }
    </style>

    <h1>Books Page</h1>
    <p>Welcome to my website</p>
    <a href="{% url 'products:create-book' %}">Add Book</a>
    <hr>

    {% for b in books %}
        <a href="{% url 'products:book-detail' b.pk %}">{{ b.title }}</a> <br><br>
    {% endfor %}
{% endblock content %}